In [1]:
import pandas as pd

In [2]:
ami_trades = pd.read_excel('SPY_20160527.xlsx', index_col='Date', parse_dates=True)
ami_trades.drop(['Trade', '% chg', 'Profit', 'Shares', 'Cum. Profit', '# bars', 'Profit/bar', 'MAE', 'MFE', 'Scale In/Out'], axis=1, inplace=True)

In [3]:
ami_trades

           Symbol   Price   Ex. date  Ex. Price  % Profit  Position value
Date
2004-05-28    SPY  112.86 2004-06-02     113.13    0.0014        99881.10
2004-11-15    SPY  118.73 2004-11-17     118.58   -0.0023        99970.66
2006-01-10    SPY  128.90 2006-01-12     128.80   -0.0018        99768.59
2007-03-22    SPY  143.18 2007-03-26     143.20   -0.0009        99653.27
2009-07-17    SPY   94.13 2009-07-21      95.57    0.0143        99589.54
2009-07-22    SPY   95.55 2009-07-24      98.06    0.0253       100996.35
2009-08-24    SPY  102.96 2009-08-26     103.17    0.0010       103474.80
2009-11-10    SPY  109.59 2009-11-12     109.03   -0.0061       103672.13
2010-03-08    SPY  114.27 2010-03-10     114.97    0.0051       102957.27
2010-03-12    SPY  115.46 2010-03-16     116.41    0.0072       103567.62
2010-03-18    SPY  117.04 2010-03-22     116.59   -0.0048       104282.64
2010-06-16    SPY  111.96 2010-06-18     111.73   -0.0031       103786.92
2012-02-06    SPY  134.46 2012-02-08     135.19    0.0044       103399.74
2012-08-20    SPY  142.22 2012-08-22     141.82   -0.0038       103820.60
2013-12-27    SPY  183.84 2013-12-31     184.69    0.0036       103501.91
2014-02-12    SPY  182.07 2014-02-14     184.02    0.0097       103779.91
2014-06-10    SPY  195.60 2014-06-12     193.54   -0.0115       104841.60
2014-06-23    SPY  195.88 2014-06-25     195.58   -0.0025       103620.52
2014-08-15    SPY  195.72 2014-08-19     198.39    0.0126       103340.16
2014-11-03    SPY  201.77 2014-11-05     202.34    0.0018       104718.63
2014-12-24    SPY  207.77 2014-12-29     208.72    0.0036       104923.85
2016-05-26    SPY  209.34 2016-05-31     209.84    0.0014       105298.02
2017-07-17    SPY  245.53 2017-07-19     246.99    0.0049       105332.37
2017-07-20    SPY  247.10 2017-07-24     246.82   -0.0021       106005.91
2017-11-29    SPY  262.71 2017-12-01     264.46    0.0057       105609.41